spring.application.name=customers-service

server.port=8080

spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:petclinic}
spring.datasource.username=${DB_USERNAME:petclinic}
spring.datasource.password=${DB_PASSWORD:petclinic}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true
