name: Customers Service CI

on:
  push:
    branches:
      - main
      - feature/**
    paths:
      - "services/customers-service/**"
      - ".github/workflows/ci.yaml"

  pull_request:
    branches:
      - main
    paths:
      - "services/customers-service/**"
      - ".github/workflows/ci.yaml"

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: services/customers-service

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: maven

      - name: Build application
        run: ./mvnw --batch-mode clean package -Dmaven.test.skip=true
